# PATHS
additional_functions_file: ./additional_functions.py
train_dataset: ./data/train
validation_dataset: ./data/val
predict_dataset: ./data/test
#load_model_path: ./CheckPoint/24_04_22__11_59/ckpt/weights.50-0.116
output_path: ./

# OPTIMIZATION OPTIONS
loss: bce_loss
optimizer:
  type: Adam
  learning_rate: 0.0001
metrics: [sum_rate_metric]

# TRAINING OPTIONS
batch_size: 16
epochs: 50
epoch_size: 500
shuffle_training_set: True
shuffle_validation_set: True
val_samples: 500
val_frequency: 1