---
# TRAINING OPTIONS
batch_size: 16
epochs: 5
epoch_size: 500
shuffle_training_set: true
shuffle_validation_set: true
val_samples: 500
val_frequency: 1
# k_best: 5
batch_norm: mean

# OPTIMIZATION OPTIONS
loss: c_bce_loss
optimizer:
  type: Adam
  beta_1: 0.9
  beta_2: 0.999
  learning_rate:  # defines the schedule here
    type: ExponentialDecay
    initial_learning_rate: 0.001
    decay_steps: 80000
    decay_rate: 0.6
metrics: [sum_rate_metric, c_binary_accuracy]

# PATHS
additional_functions_file: ./additional_functions.py
train_dataset: ./data/train
validation_dataset: ./data/test
#predict_dataset: ./data/test
output_path: ./
load_model_path: ./CheckPoint/training_500_expt_2022_06_16_11_23_54/ckpt/weights.05-0.323
